---

- name: ensure apt-transport-https is installed
  apt: name=apt-transport-https state=latest

- name: install docker apt repo key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: install docker repository with latest stable version
  apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present
  notify:
    - apt update

- name: install docker
  apt: name=lxc-docker state=latest

- get_url: url=https://github.com/docker/compose/releases/download/{{ version.docker_compose }}/docker-compose-Linux-x86_64
           dest=/usr/local/bin/docker-compose
           owner=root
           group=root
           mode=755
  ignore_errors: yes

- name: ensure docker is running and starts on bootup
  service: name=docker enabled=yes state=started
